### ISSUE TITLE
VRAM & GTT probably show wrong.

### ISSUE THREAD

**Issue by EUA** [clbr/radeontop#114]
Hi, I use 1GB GPU.
After opening lots of tabs at Firefox, under wayland
radeontop, shows VRAM > 98 GB and GTT > 300GB

Yes, if GPU memory is not enough, than some of system ram is used.
But I just have 32GB RAM at my system and info shown on radeontop looks not correct.
It has to be some bugs at driver level or radeontop.

![Screenshot from 2020-12-29 17-53-24](https://user-images.githubusercontent.com/125917/103292497-f2441100-49fe-11eb-9671-36086701b6e2.png)

**Comment by Simmonz** [comment]
I can say this issue happens with myself as well. The VRAM just starts climbing and can get to several thousand percent above what it could possibly be. 

My system:

Gigabyte R9 270 2GB | Mesa 20.3.1 | Manjaro 20.2 | Mate 1.24.1 | Kernel 5.10.2-2-MANJARO  | X11

![Radeontop VRAM Bug](https://user-images.githubusercontent.com/42974451/103401069-82747a00-4b15-11eb-8a7e-893c1046c63f.png)

**Comment by chromer030** [comment]
Same here :

![Screenshot_2021-01-07_11-10-40](https://user-images.githubusercontent.com/13361552/103865209-137cbf80-50d9-11eb-9cb8-83497aa83778.png)

Arch linux | Linux 5.10.4 | Mesa 20.3.2 | X11

**Comment by a5a5aa555oo** [comment]
Same here.
![Screenshot_2021-01-25_01-07-22](https://user-images.githubusercontent.com/48462152/105637700-b3906200-5ea9-11eb-8f51-dd896f7b8a7d.png)
Arch Linux | Linux 5.10.7-arch1-1 | mesa 20.3.2-2 | X11 | Raeon R7 240 1GB GDDR5

**Comment by satcom886** [comment]
As mentioned in #108, this is probably a kernel bug. This means that `radeontop` can't really do anything about this. We should decide if anyone here wants to open a bug report in Linux, as suggested by @clbr. We should find out approximately what kernel version this started with tho.

**Comment by satcom886** [comment]
IIRC this started at around version 5.9.x. I'm only going from memory since I didn't write it down.

**Comment by satcom886** [comment]
I just tried with 5.4.97 LTS and the values there actually seem OK. So this is indeed caused by a kernel bug.

**Comment by satcom886** [comment]
I tried a [very simple search](https://bugzilla.kernel.org/buglist.cgi?quicksearch=radeon%20memory%20usage) to see if there is already a bug report about this but it seems like there isn't.

**Comment by chromer030** [comment]
Hi everyone, I'm on kernel 5.11.1 and it seems that the issue is resolved :

![Screenshot_2021-02-24_12-45-57](https://user-images.githubusercontent.com/13361552/108978038-6e28a580-769e-11eb-9de9-d8987e33f02f.png)

**Comment by EUA** [comment]
On Linux Ryzen 5.11.8, using rx570 GPU with 4GB VRAM and it looks working proper now.

**Comment by satcom886** [comment]
I just tested with Kernel 5.11.9 on a Radeon HD 2000 Mobile Series GPU (`radeon` driver) and it still shows zero for the memory values.
